version: '3'

services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=https://timon.buzz/api
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.frontend.rule=Host(`timon.buzz`) && PathPrefix(`/`)"
    - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname

    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.backend.rule=Host(`timon.buzz`) && (PathPrefix(`/api`) || PathPrefix(`/docs`) || PathPrefix(`/redoc`))"
    - "traefik.http.services.backend.loadbalancer.server.port=8000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.adminer.rule=Host(`db.timon.buzz`)"
    - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tuitoektimon@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.timon.buzz`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - adminer
      - proxy-manager

volumes:
  postgres_data: