version: '3'
services:
  db:
    image: postgres:13
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U your_user"]
      interval: 5s
      timeout: 5s
    environment:
      POSTGRES_DB: your_user
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://your_user:your_password@db:5432/your_db_name
      condition: service_healthy