version: '3'

services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=https://timon.buzz/api

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - adminer
      - proxy-manager

volumes:
  postgres_data: